import { ChatOllama} from "@langchain/ollama";
import { ChatPromptTemplate } from "@langchain/core/prompts";

export async function generateAnswer(question: string, context: string){

    // configure the LLM we want LangChain to use

    //PURPOSE:
    // create a LangChain model object that knows how to talk to our locally running Ollama model

    // Ollama -> llama3.2:3b -> running locally on our computer

    const model = new ChatOllama({
        model: 'llama3.2:3b',
        temperature: 0
    })

    const prompt = ChatPromptTemplate.fromMessages([ 
        ['system','Answer using only the PDF context. If the answer is not in the content, say you cannot find it'],
        [
            "human",
            "CONTEXT:\n{context}\n\nQUESTION:\n{question}"
        ]
    ]);

    const formatted = await prompt.formatMessages({
        context: context,
        question: question
    })

    // send the finished prompt to Llama

    // INPUT:
    // formatted messages containing:
    // - instructions
    // - PDF context
    // - user's question

    // OUTPUT:
    // response -> AIMessage

const response = await model.invoke(formatted);


// return only the text generated by the LLM
return response.content;
}


